### ISSUE TITLE
mypy --quick-and-dirty no longer available

### ISSUE THREAD

**Issue by efroemling** [msherry/flycheck-pycheckers#27]
I just noticed that mypy has officially killed off the --quick-and-dirty option that flycheck-pycheckers uses:  
https://github.com/python/mypy/commit/b9222664310f579daf52385d248d0977aac9d2fe

Are there any plans to add support for mypy's daemon mode (the recommended replacement)?  I'd be happy to help test or take a whirl at wiring it up if it'd be helpful.  The checker still works without quick-and-dirty mode but iteration is noticably slower.

**Comment by msherry** [comment]
I wasn't aware of this change -- thanks for the heads up!

Yes, I'd love to add support for mypy's daemon mode. At a previous employer, I got used to setting the `mypy_command` to an internal script that itself used daemon mode, so I haven't done much work on enhancing mypy support lately. Now that I've moved on, I'd like to improve compatibility.

If you wanted to work on it, I'd definitely be thrilled to review a PR. Otherwise, it's on the roadmap, but I can't promise how soon I can get to it. I'll at least try to add some version detection or something so we don't use that flag if it's not supported, though.
